# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell
import pathlib

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

# The directory containing this file
HERE = pathlib.Path(__file__).parent

# The text of the README file
README = (HERE / "README.md").read_text()

setup(
    long_description=README,
    long_description_content_type='text/markdown',
    name='rsyncwrap',
    version='0.1.0',
    description='A python wrapper of rsync that yields stats updates.',
    python_requires='==3.*,>=3.8.0',
    author='Dustin Wyatt',
    author_email='dustin.wyatt@gmail.com',
    license='MIT',
    packages=['rsyncwrap'],
    install_requires=[],
    extras_require={"dev": ["wheel==0.*,>=0.34.2"]},
)
